services:
  financial-logger-mongodb:
    image: mongo:8.2
    container_name: financial-logger-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopw
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: financial-logger-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongouser:mongopw@financial-logger-mongodb:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: expressuser
      ME_CONFIG_BASICAUTH_PASSWORD: expresspw
    depends_on:
      - financial-logger-mongodb

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: financial-logger-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: mongodb://admin:password@mongodb:27017/financial_logger?authSource=admin
      NODE_ENV: dev
    depends_on:
      - financial-logger-mongodb

volumes:
  mongodb_data:
