version: "3.8"

services:
  financial-logger-mongodb:
    image: mongo:8.2
    container_name: financial-logger-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpw
      MONGO_INITDB_DATABASE: financialLoggerDb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:adminpw@financial-logger-mongodb:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: expressuser
      ME_CONFIG_BASICAUTH_PASSWORD: expresspw
  
  financial-logger:
    build: .
    container_name: financial-logger
    ports:
      - "3000:3000"

volumes:
  mongodb_data:
  mongodb_config:

networks:
  default:
    external:
      name: financial-logger