export enum ErrorCode {
    REQUEST_IS_NULL_OR_UNDEFINED = 'REQUEST_IS_NULL_OR_UNDEFINED',
    MISSING_PARAMETER = 'MISSING_PARAMETER',
    MISSING_REQUEST_BODY = 'MISSING_REQUEST_BODY',
    UNAUTHORIZED = 'UNAUTHORIZED'
}